import ballista_1 from "../assets/Northern Realms/troops/Ballista 1.png";
import ballista_2 from "../assets/Northern Realms/troops/Ballista 2.png";
import blue_stripes_commando from "../assets/Northern Realms/troops/Blue Stripes Commando.png";
import catapult from "../assets/Northern Realms/troops/Catapult.png";
import crinfrid_reavers_dragon_hunter from "../assets/Northern Realms/troops/Crinfrid Reavers Dragon Hunter.png";
import dethmold from "../assets/Northern Realms/troops/Dethmold.png";
import dun_banner_medic from "../assets/Northern Realms/troops/Dun Banner Medic.png";
import esterad_thyssen from "../assets/Northern Realms/troops/Esterad Thyssen.png";
import john_natalis from "../assets/Northern Realms/troops/John Natalis.png";
import kaedweni_siege_expert from "../assets/Northern Realms/troops/Kaedweni Siege Expert.png";
import keira_metz from "../assets/Northern Realms/troops/Keira Metz.png";
import phillipa_eilhart from "../assets/Northern Realms/troops/Philippa Eilhart.png";
import poor_fucking_infantry from "../assets/Northern Realms/troops/Poor Fucking Infantry.png";
import prince_stennis from "../assets/Northern Realms/troops/Prince Stennis.png";
import redanian_foot_soldier_1 from "../assets/Northern Realms/troops/Redanian Foot Soldier 1.png";
import redanian_foot_soldier_2 from "../assets/Northern Realms/troops/Redanian Foot Soldier 2.png";
import sabrina_glevissig from "../assets/Northern Realms/troops/Sabrina Glevissig.png";
import sheldon_skaggs from "../assets/Northern Realms/troops/Shelden Skaggs.png";
import siege_tower from "../assets/Northern Realms/troops/Siege Tower.png";
import siegfried_of_denesle from "../assets/Northern Realms/troops/Siegfried of Denesle.png";
import sigismund_dijkstra from "../assets/Northern Realms/troops/Sigismund Dijkstra.png";
import sile_de_tansarville from "../assets/Northern Realms/troops/Sile de Tansarville.png";
import thaler from "../assets/Northern Realms/troops/Thaler.png";
import trebuchet_1 from "../assets/Northern Realms/troops/Trebuchet  1.png";
import trebuchet_2 from "../assets/Northern Realms/troops/Trebuchet  2.png";
import vernon_roche from "../assets/Northern Realms/troops/Vernon Roche.png";
import ves from "../assets/Northern Realms/troops/Ves.png";
import yarpen_zigrin from "../assets/Northern Realms/troops/Yarpen Zigrin.png";
import scorch from "../assets/Neutrals/Scorch.png";
import type { CompleteCardProps } from "../UI_Elements/CompleteCard";
import { Glimmers, Shadows } from "../UI_Elements/UI_Utilities";
import { CardSpecials } from "./game_types/CardSpecials";

import { CardClass, type CardType } from "./game_types/RowType";

const northernRealms: CompleteCardProps[] = [
  {
    name: "Ballista",
    img: ballista_1,
    damage: 6,
    cardClass: CardClass.SUPPORT,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Ballista",
    img: ballista_2,
    damage: 6,
    cardClass: CardClass.SUPPORT,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Blue Stripes Commando",
    img: blue_stripes_commando,
    damage: 4,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.TIGHT_BOND,
  },
  {
    name: "Catapult",
    img: catapult,
    damage: 8,
    cardClass: CardClass.SUPPORT,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Crinfrid Reavers Dragon Hunter",
    img: crinfrid_reavers_dragon_hunter,
    damage: 5,
    cardClass: CardClass.RANGED,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.TIGHT_BOND,
  },
  {
    name: "Dethmold",
    img: dethmold,
    damage: 6,
    cardClass: CardClass.RANGED,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Dun Banner Medic",
    img: dun_banner_medic,
    damage: 5,
    cardClass: CardClass.SUPPORT,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.MEDIC,
  },
  {
    name: "Esterad Thyssen",
    img: esterad_thyssen,
    damage: 10,
    cardClass: CardClass.MELEE,
    isHero: true,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "John Natalis",
    img: john_natalis,
    damage: 10,
    cardClass: CardClass.MELEE,
    isHero: true,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Kaedweni Siege Expert",
    img: kaedweni_siege_expert,
    damage: 1,
    cardClass: CardClass.SUPPORT,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.MORALE,
  },
  {
    name: "Keira Metz",
    img: keira_metz,
    damage: 5,
    cardClass: CardClass.RANGED,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Philippa Eilhart",
    img: phillipa_eilhart,
    damage: 10,
    cardClass: CardClass.RANGED,
    isHero: true,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Poor Fucking Infantry",
    img: poor_fucking_infantry,
    damage: 1,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Prince Stennis",
    img: prince_stennis,
    damage: 1,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.SPY,
  },
  {
    name: "Redanian Foot Soldier",
    img: redanian_foot_soldier_1,
    damage: 1,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Redanian Foot Soldier",
    img: redanian_foot_soldier_2,
    damage: 1,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Sabrina Glevissig",
    img: sabrina_glevissig,
    damage: 1,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Sheldon Skaggs",
    img: sheldon_skaggs,
    damage: 1,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Siege Tower",
    img: siege_tower,
    damage: 1,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Siegfried of Denesle",
    img: siegfried_of_denesle,
    damage: 1,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Sigismund Dijkstra",
    img: sigismund_dijkstra,
    damage: 1,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.SPY,
  },
  {
    name: "Síle de Tansarville ",
    img: sile_de_tansarville,
    damage: 1,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Thaler",
    img: thaler,
    damage: 1,
    cardClass: CardClass.SUPPORT,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.SPY,
  },
  {
    name: "Trebuchet",
    img: trebuchet_1,
    damage: 1,
    cardClass: CardClass.SUPPORT,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Trebuchet",
    img: trebuchet_2,
    damage: 1,
    cardClass: CardClass.SUPPORT,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Vernon Roche",
    img: vernon_roche,
    damage: 1,
    cardClass: CardClass.SUPPORT,
    isHero: true,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Ves",
    img: ves,
    damage: 1,
    cardClass: CardClass.SUPPORT,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Yarpen Zigrin",
    img: yarpen_zigrin,
    damage: 1,
    cardClass: CardClass.SUPPORT,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.WHITE,
    center: 50,
    cardSpecial: CardSpecials.NONE,
  },
  {
    name: "Scorch",
    img: scorch,
    damage: 2,
    cardClass: CardClass.MELEE,
    isHero: false,
    shadow: Shadows.BLUE,
    glimmer: Glimmers.GOLD,
    center: 50,
    cardSpecial: CardSpecials.SCORCH,
  },
];

export default northernRealms;
